- hosts: localhost
  tasks:
    # - include: tasks/snapd.yaml
    #- include: tasks/apt-add-repositories.yaml
    - include: tasks/dpkg.yaml
    # - include: tasks/apt.yaml
    # - include: tasks/docker.yaml
    # - include: tasks/configure-git.yaml
